- name: Create database namespace
  community.kubernetes.k8s:
    name: "{{ namespace }}"
    api_version: v1
    kind: namespace
    state: present

- name: Add Bitnami Repo
  community.kubernetes.helm_repository:
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"

- name: Apply Postgresql Secrets
  kubernetes.core.helm:
    name: "{{ deployment }}-secret"
    chart_ref: ./roles/postgresql/files/global
    release_namespace: "{{ namespace }}"
    release_values:
      postgresqlPassword: "{{ postgrespassword }}"

- name: Apply Postgresql Database
  kubernetes.core.helm:
    name: "{{ deployment }}"
    chart_ref: bitnami/postgresql
    release_namespace: "{{ namespace }}"
    release_values:
      global:
        storageClass: "nfs-nas"
        postgresql:
          postgresqlUsername: "postgres"
          postgresqlDatabase: "postgresqldb"
          existingSecret: "postgresqlpassword"
      image:
        repository: "postgres"
        tag: "13.4"
      service:
        type: "{{ serviceType }}"
        loadBalancerIP: "192.168.137.72"
      namespace: "{{ namespace }}"

