- name: Create database namespace
  kubernetes.core.k8s:
    name: "{{ namespace }}"
    api_version: v1
    kind: namespace
    state: present

- name: Add Bitnami Repo
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"

- name: Apply Postgresql Persistence
  kubernetes.core.helm:
    name: "{{ deployment }}-persistence"
    chart_ref: ./roles/postgresql/files/persistence
    release_namespace: "{{ namespace }}"

- name: Apply Postgresql Secrets
  kubernetes.core.helm:
    name: "{{ deployment }}-secrets"
    chart_ref: ./roles/postgresql/files/secrets
    release_namespace: "{{ namespace }}"
    release_values:
      postgresqlPassword: "{{ postgrespassword }}"

- name: Apply Postgresql Database
  kubernetes.core.helm:
    name: "{{ deployment }}"
    chart_ref: bitnami/postgresql
    release_namespace: "{{ namespace }}"
    release_values:
      global:
        postgresql:
          postgresqlUsername: "postgres"
          postgresqlDatabase: "postgresqldb"
          existingSecret: "postgresqlpassword"
      image:
        repository: "postgres"
        tag: "13.4"
      service:
        type: "{{ serviceType }}"
        loadBalancerIP: "192.168.137.72"
      namespace: "{{ namespace }}"
      persistence:
        existingClaim: "postgres-pvc"
        storageClass: ""
        mountPath: "/var/postgresql"
      postgresqlDataDir: "/var/postgresql/data"
      securityContext:
        fsGroup: 0
      containerSecurityContext:
        enabled: true
        runAsUser: 0
