apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: postgres-pvc
    namespace: database
  iscsi:
    chapAuthSession: false
    chapAuthDiscovery: false
    targetPortal: 192.168.137.3:3260
    iqn: 'iqn.2000-01.com.synology:drive.postgres.402fcc5ed94'
    lun: 01
    fsType: 'ext4'
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: database
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  volumeName: "postgres-pv"