# Reset database and db creds.
- name: Uninstall Postgresql
  hosts: localhost
  vars:
    dbnamespace: build

- name: Reset Postgresql
  hosts: localhost
  tasks:
    - name: Uninstall Postgresql
      command: helm uninstall -n "{{ dbnamespace }}" postgresql
      delegate_to: localhost
      ignore_errors: true

    - name: Uninstall Postgresql
      command: helm uninstall -n "{{ dbnamespace }}" postgresql-secret
      delegate_to: localhost
