---
# Secrets
apiVersion: v1
kind: Secret
metadata:
  name: postgresqlpassword
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  postgresql-password: {{ .Values.postgresqlPassword | b64enc }}
  postgresql-postgres-password: {{ .Values.postgresqlPassword | b64enc }}