- name: Install Postgresql
  hosts: localhost
  vars_files: files/postgres-creds.yaml
  vars:
    namespace: database

  tasks:
    - name: Install Openshift Python Library
      command: pip3 install openshift
      delegate_to: localhost

    - name: Install Ansible
      become: true
      apt:
        name: ansible
        state: present
        update_cache: yes
      delegate_to: localhost

    - name: Install Ansible Galaxy Kubernetes
      command: ansible-galaxy collection install community.kubernetes
      delegate_to: localhost

    - name: Create database namespace
      community.kubernetes.k8s:
        name: "{{ namespace }}"
        api_version: v1
        kind: namespace
        state: present
      delegate_to: localhost

    - name: Add Bitnami Repo
      community.kubernetes.helm_repository:
        name: bitnami
        repo_url: "https://charts.bitnami.com/bitnami"
      delegate_to: localhost

    - name: Copy Secret Chart
      copy:
        src: ../postgresql
        dest: /tmp/
      delegate_to: localhost

    - name: Copy Customization
      copy:
        src: ../postgresql-values.yaml
        dest: /tmp/
      delegate_to: localhost

    - name: Apply Postgresql Database
      command: >
        helm install -n "{{ namespace }}" postgresql-secret /tmp/postgresql
        --set namespace="{{ namespace }}"
        --set postgresqlPassword="{{ postgrespassword }}"
      delegate_to: localhost

#  -f /tmp/postgresql-values.yaml
    - name: Apply Postgresql Database
      command: >
        helm install -n "{{ namespace }}" postgresql bitnami/postgresql
        --set global.storageClass="nfs-nas"
        --set global.postgresql.postgresqlUsername="postgres"
        --set global.postgresql.postgresqlDatabase="postgresqldb"
        --set global.postgresql.existingSecret="postgresqlpassword"
        --set image.repository="postgres"
        --set image.tag="13.4"
        --set service.type="LoadBalancer"
        --set service.loadBalancerIP="192.168.137.72"
        --set namespace="{{ namespace }}"
      delegate_to: localhost
